# Generated by Django 5.2.9 on 2026-02-13 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_paycheck_second_day_of_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='related_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='api.recurringbill'),
        ),
    ]
