# Generated by Django 5.2.9 on 2026-02-13 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_expense_related_bill"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="finance_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="api.financeaccount",
            ),
        ),
        migrations.AddField(
            model_name="paycheck",
            name="finance_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paychecks",
                to="api.financeaccount",
            ),
        ),
        migrations.AddField(
            model_name="recurringbill",
            name="finance_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_bills",
                to="api.financeaccount",
            ),
        ),
    ]
