# Generated by Django 5.2.9 on 2026-02-15 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_categories(apps, schema_editor):
    Category = apps.get_model("api", "Category")
    RecurringBill = apps.get_model("api", "RecurringBill")
    Expense = apps.get_model("api", "Expense")

    # Migrate RecurringBill categories
    for bill in RecurringBill.objects.all():
        if hasattr(bill, "category_old") and bill.category_old:
            cat_name = bill.category_old.strip()
            if cat_name:
                category, _ = Category.objects.get_or_create(
                    user=bill.user, name=cat_name, defaults={"type": "bill"}
                )
                bill.category = category
                bill.save()

    # Migrate Expense categories
    for expense in Expense.objects.all():
        if hasattr(expense, "category_old") and expense.category_old:
            cat_name = expense.category_old.strip()
            if cat_name:
                category, _ = Category.objects.get_or_create(
                    user=expense.user, name=cat_name, defaults={"type": "expense"}
                )
                expense.category = category
                expense.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_expense_finance_account_paycheck_finance_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringbill",
            name="color",
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("bill", "Bill"),
                            ("general", "General"),
                        ],
                        default="general",
                        help_text="Defines if this category is typically for income, expenses, or bills.",
                        max_length=10,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("bg-red-500", "Red"),
                            ("bg-rose-500", "Rose"),
                            ("bg-orange-500", "Orange"),
                            ("bg-amber-500", "Amber"),
                            ("bg-yellow-500", "Yellow"),
                            ("bg-lime-500", "Lime"),
                            ("bg-green-500", "Green"),
                            ("bg-emerald-500", "Emerald"),
                            ("bg-teal-500", "Teal"),
                            ("bg-cyan-500", "Cyan"),
                            ("bg-sky-500", "Sky"),
                            ("bg-blue-500", "Blue"),
                            ("bg-indigo-500", "Indigo"),
                            ("bg-violet-500", "Violet"),
                            ("bg-purple-500", "Purple"),
                            ("bg-fuchsia-500", "Fuchsia"),
                            ("bg-pink-500", "Pink"),
                            ("bg-gray-500", "Gray"),
                        ],
                        default="bg-gray-500",
                        help_text="Tailwind CSS background color class for this category.",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "unique_together": {("user", "name")},
            },
        ),
        migrations.RenameField(
            model_name="recurringbill",
            old_name="category",
            new_name="category_old",
        ),
        migrations.AddField(
            model_name="recurringbill",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="The category this recurring bill belongs to.",
                limit_choices_to={"type__in": ["bill", "expense", "general"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_bills",
                to="api.category",
            ),
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="category",
            new_name="category_old",
        ),
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="The category this expense belongs to.",
                limit_choices_to={"type__in": ["expense", "general"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="api.category",
            ),
        ),
        migrations.AddField(
            model_name="paycheck",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="The category this paycheck belongs to (e.g., Salary, Freelance).",
                limit_choices_to={"type__in": ["income", "general"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paychecks",
                to="api.category",
            ),
        ),
        migrations.RunPython(migrate_categories),
        migrations.RemoveField(
            model_name="recurringbill",
            name="category_old",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="category_old",
        ),
    ]
