# Generated by Django 5.2.9 on 2026-02-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_recurringbill_color_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                choices=[
                    ("red-500", "Red"),
                    ("rose-500", "Rose"),
                    ("orange-500", "Orange"),
                    ("amber-500", "Amber"),
                    ("yellow-500", "Yellow"),
                    ("lime-500", "Lime"),
                    ("green-500", "Green"),
                    ("emerald-500", "Emerald"),
                    ("teal-500", "Teal"),
                    ("cyan-500", "Cyan"),
                    ("sky-500", "Sky"),
                    ("blue-500", "Blue"),
                    ("indigo-500", "Indigo"),
                    ("violet-500", "Violet"),
                    ("purple-500", "Purple"),
                    ("fuchsia-500", "Fuchsia"),
                    ("pink-500", "Pink"),
                    ("gray-500", "Gray"),
                ],
                default="bg-gray-500",
                help_text="Tailwind CSS background color class for this category.",
                max_length=15,
            ),
        ),
    ]
