# Generated by Django 5.2.9 on 2026-03-16 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_savingsrecurringdeposit_is_payroll_deposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringbill",
            name="day_of_week",
            field=models.IntegerField(
                blank=True,
                help_text="Day of week for weekly/biweekly bills (0=Monday, 6=Sunday)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recurringbill",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("once", "Once"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="monthly",
                help_text="How often this bill recurs (once, weekly, biweekly, monthly)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recurringbill",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="The first date this bill is due"
            ),
        ),
        migrations.AlterField(
            model_name="recurringbill",
            name="due_day",
            field=models.IntegerField(
                blank=True, help_text="Day of month for monthly bills (1-31)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="savingsrecurringdeposit",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("once", "Once"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
    ]
