# Generated by Django 5.2.9 on 2026-03-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_recurringbill_day_of_week_recurringbill_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
