/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/routes/__root";
import { Route as FinanceRouteImport } from "./app/routes/_finance";
import { Route as FinanceSettingsRouteImport } from "./app/routes/_finance/settings";
import { Route as FinancePriorityRouteImport } from "./app/routes/_finance/priority";
import { Route as FinanceDashboardRouteImport } from "./app/routes/_finance/dashboard";

const FinanceRoute = FinanceRouteImport.update({
  id: "/_finance",
  getParentRoute: () => rootRouteImport,
} as any);
const FinanceSettingsRoute = FinanceSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => FinanceRoute,
} as any);
const FinancePriorityRoute = FinancePriorityRouteImport.update({
  id: "/priority",
  path: "/priority",
  getParentRoute: () => FinanceRoute,
} as any);
const FinanceDashboardRoute = FinanceDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => FinanceRoute,
} as any);

export interface FileRoutesByFullPath {
  "/dashboard": typeof FinanceDashboardRoute;
  "/priority": typeof FinancePriorityRoute;
  "/settings": typeof FinanceSettingsRoute;
}
export interface FileRoutesByTo {
  "/dashboard": typeof FinanceDashboardRoute;
  "/priority": typeof FinancePriorityRoute;
  "/settings": typeof FinanceSettingsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_finance": typeof FinanceRouteWithChildren;
  "/_finance/dashboard": typeof FinanceDashboardRoute;
  "/_finance/priority": typeof FinancePriorityRoute;
  "/_finance/settings": typeof FinanceSettingsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/dashboard" | "/priority" | "/settings";
  fileRoutesByTo: FileRoutesByTo;
  to: "/dashboard" | "/priority" | "/settings";
  id:
    | "__root__"
    | "/_finance"
    | "/_finance/dashboard"
    | "/_finance/priority"
    | "/_finance/settings";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  FinanceRoute: typeof FinanceRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_finance": {
      id: "/_finance";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof FinanceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_finance/settings": {
      id: "/_finance/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof FinanceSettingsRouteImport;
      parentRoute: typeof FinanceRoute;
    };
    "/_finance/priority": {
      id: "/_finance/priority";
      path: "/priority";
      fullPath: "/priority";
      preLoaderRoute: typeof FinancePriorityRouteImport;
      parentRoute: typeof FinanceRoute;
    };
    "/_finance/dashboard": {
      id: "/_finance/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof FinanceDashboardRouteImport;
      parentRoute: typeof FinanceRoute;
    };
  }
}

interface FinanceRouteChildren {
  FinanceDashboardRoute: typeof FinanceDashboardRoute;
  FinancePriorityRoute: typeof FinancePriorityRoute;
  FinanceSettingsRoute: typeof FinanceSettingsRoute;
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceDashboardRoute: FinanceDashboardRoute,
  FinancePriorityRoute: FinancePriorityRoute,
  FinanceSettingsRoute: FinanceSettingsRoute,
};

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  FinanceRoute: FinanceRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
